import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Instagram Chat",
  description: "Generated by Alejandro Alcocer",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // TODO: Replace with actual theme state (e.g., localStorage, user preferences)
  const light_theme = true;

  return (
    <html lang="en" className={light_theme ? "" : "dark"}>
      <body className="antialiased bg-white dark:bg-gray-900 text-gray-900 dark:text-gray-100">
        {children}
      </body>
    </html>
  );
}
