import './globals.css';
import Providers from '@/components/Providers';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Instagram Chat',
    description: 'Generated by Alejandro Alcocer',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
